version: '3.1'

services:

  database:
    image: postgres:14.2
    restart: always
    container_name: text2sql-database
    networks:
      - local-machine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: text2sql-poc
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5442:5432

volumes:
  init.sh:

networks: 
  local-machine:
    driver: bridge 